// <auto-generated />
using System;
using Eventfully.Samples.ConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eventfully.Samples.ConsoleApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Messaging.EFCoreOutbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("ExpiresAtUtc");

                    b.Property<DateTime>("PriorityDateUtc");

                    b.Property<int>("Status");

                    b.Property<int>("TryCount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("PriorityDateUtc", "Status")
                        .HasName("IX_PriorityDateUtc")
                        .HasAnnotation("SqlServer:Include", new[] { "TryCount", "Type", "ExpiresAtUtc", "CreatedAtUtc", "Endpoint" });

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Messaging.EFCoreOutbox.OutboxMessage+OutboxMessageData", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<byte[]>("Data")
                        .IsRequired();

                    b.Property<string>("MetaData");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessageData");
                });

            modelBuilder.Entity("Messaging.EFCoreOutbox.OutboxMessage+OutboxMessageData", b =>
                {
                    b.HasOne("Messaging.EFCoreOutbox.OutboxMessage")
                        .WithOne("MessageData")
                        .HasForeignKey("Messaging.EFCoreOutbox.OutboxMessage+OutboxMessageData", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
